// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScientificAuthorsDB.Data;

#nullable disable

namespace ScientificAuthorsDB.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260513133057_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ScientificAuthorsDB.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BirthYear")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OrcidId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthYear = 1985,
                            Email = "avaswani@google.com",
                            FirstName = "Ашиш",
                            LastName = "Васвани",
                            OrcidId = "0000-0001-1111-0001"
                        },
                        new
                        {
                            Id = 2,
                            BirthYear = 1976,
                            Email = "noam@google.com",
                            FirstName = "Ноам",
                            LastName = "Шазиър",
                            OrcidId = "0000-0001-1111-0002"
                        },
                        new
                        {
                            Id = 3,
                            BirthYear = 1988,
                            Email = "illia@near.org",
                            FirstName = "Илия",
                            LastName = "Полосухин",
                            OrcidId = "0000-0001-1111-0003"
                        },
                        new
                        {
                            Id = 4,
                            BirthYear = 1990,
                            Email = "w.wang@se-research.org",
                            FirstName = "Уентинг",
                            LastName = "Уанг",
                            OrcidId = "0000-0001-1111-0004"
                        },
                        new
                        {
                            Id = 5,
                            BirthYear = 1989,
                            Email = "x.niu@se-research.org",
                            FirstName = "Сяотинг",
                            LastName = "Ниу",
                            OrcidId = "0000-0001-1111-0005"
                        },
                        new
                        {
                            Id = 6,
                            BirthYear = 1952,
                            Email = "unclebob@cleancoder.com",
                            FirstName = "Робърт С.",
                            LastName = "Мартин",
                            OrcidId = "0000-0001-1111-0006"
                        },
                        new
                        {
                            Id = 101,
                            BirthYear = 1975,
                            Email = "ivan@su.bg",
                            FirstName = "Иван",
                            LastName = "Петров",
                            OrcidId = "0000-0001-2345-6789"
                        },
                        new
                        {
                            Id = 102,
                            BirthYear = 1980,
                            Email = "maria@bas.bg",
                            FirstName = "Мария",
                            LastName = "Иванова",
                            OrcidId = "0000-0002-9876-5432"
                        },
                        new
                        {
                            Id = 103,
                            BirthYear = 1990,
                            Email = "g.dimitrov@tu.bg",
                            FirstName = "Георги",
                            LastName = "Димитров",
                            OrcidId = "0000-0003-1111-2222"
                        },
                        new
                        {
                            Id = 104,
                            BirthYear = 1978,
                            Email = "jsmith@mit.edu",
                            FirstName = "Джон",
                            LastName = "Смит",
                            OrcidId = "0000-0002-4444-5555"
                        },
                        new
                        {
                            Id = 105,
                            BirthYear = 1985,
                            Email = "elena.n@mu-plovdiv.bg",
                            FirstName = "Елена",
                            LastName = "Николова",
                            OrcidId = "0000-0001-7777-8888"
                        },
                        new
                        {
                            Id = 106,
                            BirthYear = 1982,
                            Email = "alice.j@oxford.ac.uk",
                            FirstName = "Алис",
                            LastName = "Джонсън",
                            OrcidId = "0000-0002-3333-6666"
                        },
                        new
                        {
                            Id = 107,
                            BirthYear = 1970,
                            Email = "p.todorov@unwe.bg",
                            FirstName = "Петър",
                            LastName = "Тодоров",
                            OrcidId = "0000-0003-9999-0000"
                        },
                        new
                        {
                            Id = 108,
                            BirthYear = 1965,
                            Email = "hmuller@mpg.de",
                            FirstName = "Ханс",
                            LastName = "Мюлер",
                            OrcidId = "0000-0001-5555-4444"
                        },
                        new
                        {
                            Id = 109,
                            BirthYear = 1988,
                            Email = "smiteva@cern.ch",
                            FirstName = "Силвия",
                            LastName = "Митева",
                            OrcidId = "0000-0002-1234-5678"
                        },
                        new
                        {
                            Id = 110,
                            BirthYear = 1992,
                            Email = "rbrown@stanford.edu",
                            FirstName = "Робърт",
                            LastName = "Браун",
                            OrcidId = "0000-0002-8888-1111"
                        });
                });

            modelBuilder.Entity("ScientificAuthorsDB.Models.AuthorInstitution", b =>
                {
                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("int");

                    b.Property<int?>("EndYear")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StartYear")
                        .HasColumnType("int");

                    b.HasKey("AuthorId", "InstitutionId");

                    b.HasIndex("InstitutionId");

                    b.ToTable("AuthorInstitutions");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            InstitutionId = 1,
                            Role = "Старши изследовател",
                            StartYear = 2016
                        },
                        new
                        {
                            AuthorId = 2,
                            InstitutionId = 1,
                            Role = "Главен инженер",
                            StartYear = 2015
                        },
                        new
                        {
                            AuthorId = 3,
                            InstitutionId = 1,
                            Role = "Изследовател",
                            StartYear = 2017
                        },
                        new
                        {
                            AuthorId = 4,
                            InstitutionId = 104,
                            Role = "Доцент",
                            StartYear = 2019
                        },
                        new
                        {
                            AuthorId = 5,
                            InstitutionId = 104,
                            Role = "Изследовател",
                            StartYear = 2020
                        },
                        new
                        {
                            AuthorId = 6,
                            InstitutionId = 102,
                            Role = "Софтуерен консултант",
                            StartYear = 2001
                        },
                        new
                        {
                            AuthorId = 101,
                            InstitutionId = 101,
                            Role = "Професор",
                            StartYear = 2010
                        },
                        new
                        {
                            AuthorId = 101,
                            InstitutionId = 103,
                            Role = "Гост-изследовател",
                            StartYear = 2015
                        },
                        new
                        {
                            AuthorId = 102,
                            InstitutionId = 103,
                            Role = "Главен асистент",
                            StartYear = 2012
                        },
                        new
                        {
                            AuthorId = 103,
                            InstitutionId = 105,
                            Role = "Доцент",
                            StartYear = 2018
                        },
                        new
                        {
                            AuthorId = 104,
                            InstitutionId = 102,
                            Role = "Професор",
                            StartYear = 2005
                        },
                        new
                        {
                            AuthorId = 105,
                            InstitutionId = 108,
                            Role = "Асистент",
                            StartYear = 2020
                        },
                        new
                        {
                            AuthorId = 106,
                            InstitutionId = 104,
                            Role = "Изследовател",
                            StartYear = 2016
                        },
                        new
                        {
                            AuthorId = 107,
                            InstitutionId = 110,
                            Role = "Професор",
                            StartYear = 2008
                        },
                        new
                        {
                            AuthorId = 108,
                            InstitutionId = 109,
                            Role = "Директор",
                            StartYear = 2000
                        },
                        new
                        {
                            AuthorId = 109,
                            InstitutionId = 106,
                            Role = "Физик",
                            StartYear = 2019
                        },
                        new
                        {
                            AuthorId = 110,
                            InstitutionId = 107,
                            Role = "Докторант",
                            StartYear = 2021
                        });
                });

            modelBuilder.Entity("ScientificAuthorsDB.Models.AuthorPublication", b =>
                {
                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("PublicationId")
                        .HasColumnType("int");

                    b.Property<int?>("AuthorOrder")
                        .HasColumnType("int");

                    b.Property<string>("ContributionRole")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuthorId", "PublicationId");

                    b.HasIndex("PublicationId");

                    b.ToTable("AuthorPublications");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            PublicationId = 1,
                            AuthorOrder = 1,
                            ContributionRole = "Водещ автор"
                        },
                        new
                        {
                            AuthorId = 2,
                            PublicationId = 1,
                            AuthorOrder = 2,
                            ContributionRole = "Съавтор"
                        },
                        new
                        {
                            AuthorId = 3,
                            PublicationId = 1,
                            AuthorOrder = 3,
                            ContributionRole = "Съавтор"
                        },
                        new
                        {
                            AuthorId = 4,
                            PublicationId = 2,
                            AuthorOrder = 1,
                            ContributionRole = "Водещ автор"
                        },
                        new
                        {
                            AuthorId = 5,
                            PublicationId = 2,
                            AuthorOrder = 2,
                            ContributionRole = "Съавтор"
                        },
                        new
                        {
                            AuthorId = 6,
                            PublicationId = 3,
                            AuthorOrder = 1,
                            ContributionRole = "Единствен автор"
                        },
                        new
                        {
                            AuthorId = 101,
                            PublicationId = 101,
                            AuthorOrder = 1,
                            ContributionRole = "Водещ автор"
                        },
                        new
                        {
                            AuthorId = 105,
                            PublicationId = 101,
                            AuthorOrder = 2,
                            ContributionRole = "Съавтор"
                        },
                        new
                        {
                            AuthorId = 109,
                            PublicationId = 102,
                            AuthorOrder = 1,
                            ContributionRole = "Водещ автор"
                        },
                        new
                        {
                            AuthorId = 104,
                            PublicationId = 102,
                            AuthorOrder = 2,
                            ContributionRole = "Съавтор"
                        },
                        new
                        {
                            AuthorId = 107,
                            PublicationId = 103,
                            AuthorOrder = 1,
                            ContributionRole = "Водещ автор"
                        },
                        new
                        {
                            AuthorId = 110,
                            PublicationId = 103,
                            AuthorOrder = 2,
                            ContributionRole = "Съавтор"
                        },
                        new
                        {
                            AuthorId = 105,
                            PublicationId = 104,
                            AuthorOrder = 1,
                            ContributionRole = "Единствен автор"
                        },
                        new
                        {
                            AuthorId = 103,
                            PublicationId = 105,
                            AuthorOrder = 1,
                            ContributionRole = "Водещ автор"
                        },
                        new
                        {
                            AuthorId = 108,
                            PublicationId = 105,
                            AuthorOrder = 2,
                            ContributionRole = "Съавтор"
                        });
                });

            modelBuilder.Entity("ScientificAuthorsDB.Models.Institution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Institutions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Маунтин Вю",
                            Country = "САЩ",
                            Name = "Google Brain",
                            Type = "Изследователски център",
                            Website = "https://research.google"
                        },
                        new
                        {
                            Id = 101,
                            City = "София",
                            Country = "България",
                            Name = "Софийски университет",
                            Type = "Университет",
                            Website = "https://www.uni-sofia.bg"
                        },
                        new
                        {
                            Id = 102,
                            City = "Кеймбридж",
                            Country = "САЩ",
                            Name = "МИТ (MIT)",
                            Type = "Университет",
                            Website = "https://www.mit.edu"
                        },
                        new
                        {
                            Id = 103,
                            City = "София",
                            Country = "България",
                            Name = "БАН",
                            Type = "Изследователски център",
                            Website = "https://www.bas.bg"
                        },
                        new
                        {
                            Id = 104,
                            City = "Оксфорд",
                            Country = "Великобритания",
                            Name = "Оксфордски университет",
                            Type = "Университет",
                            Website = "https://www.ox.ac.uk"
                        },
                        new
                        {
                            Id = 105,
                            City = "София",
                            Country = "България",
                            Name = "Технически университет",
                            Type = "Университет",
                            Website = "https://tu-sofia.bg"
                        },
                        new
                        {
                            Id = 106,
                            City = "Женева",
                            Country = "Швейцария",
                            Name = "ЦЕРН",
                            Type = "Изследователски център",
                            Website = "https://home.cern"
                        },
                        new
                        {
                            Id = 107,
                            City = "Станфорд",
                            Country = "САЩ",
                            Name = "Станфордски университет",
                            Type = "Университет",
                            Website = "https://www.stanford.edu"
                        },
                        new
                        {
                            Id = 108,
                            City = "Пловдив",
                            Country = "България",
                            Name = "Медицински университет",
                            Type = "Университет",
                            Website = "https://mu-plovdiv.bg"
                        },
                        new
                        {
                            Id = 109,
                            City = "Мюнхен",
                            Country = "Германия",
                            Name = "Институт 'Макс Планк'",
                            Type = "Изследователски център",
                            Website = "https://www.mpg.de"
                        },
                        new
                        {
                            Id = 110,
                            City = "София",
                            Country = "България",
                            Name = "УНСС",
                            Type = "Университет",
                            Website = "https://www.unwe.bg"
                        });
                });

            modelBuilder.Entity("ScientificAuthorsDB.Models.Publication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abstract")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Doi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Journal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Publications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abstract = "Доминиращите модели за преобразуване на последователности се основават на сложни рекурентни или конволюционни невронни мрежи. Ние предлагаме нова проста мрежова архитектура, наречена Transformer (Трансформатор), базирана изцяло на механизми за внимание, като напълно премахва необходимостта от рекурентност и конволюции.",
                            Doi = "10.48550/arXiv.1706.03762",
                            Journal = "31-ва Конференция по системи за обработка на невронна информация (NIPS)",
                            PublicationType = "Доклад от конференция",
                            Title = "Вниманието е всичко, от което имате нужда",
                            Year = 2017
                        },
                        new
                        {
                            Id = 2,
                            Abstract = "Ние систематично анализираме скорошни публикации по софтуерно инженерство, за да изследваме наличието, местоположението, форматите и дълготрайността на споделените артефакти. Нашите открития предоставят изчерпателен преглед на текущите практики и насоки за бъдещи възпроизводими изследвания.",
                            Doi = "10.1016/j.jss.2024.112032",
                            Journal = "Журнал за системи и софтуер",
                            PublicationType = "Научна статия",
                            Title = "Изследователски артефакти в публикациите по софтуерно инженерство: Състояние и тенденции",
                            Year = 2024
                        },
                        new
                        {
                            Id = 3,
                            Abstract = "Дори лошият код може да функционира. Но ако кодът не е чист, той може да срине една организация за разработка. Тази книга ви учи как да пишете чист, лесен за поддръжка и четим код, превръщайки ви в истински софтуерен майстор.",
                            Doi = "9780132350884",
                            Journal = "Издателство Prentice Hall",
                            PublicationType = "Книга",
                            Title = "Чист код: Наръчник за гъвкаво софтуерно майсторство",
                            Year = 2008
                        },
                        new
                        {
                            Id = 101,
                            Abstract = "Изследване на приложението на невронни мрежи за ранна диагностика.",
                            Doi = "10.1038/s41586-022-00001",
                            Journal = "Природа",
                            PublicationType = "Научна статия",
                            Title = "Машинно обучение в здравеопазването",
                            Year = 2022
                        },
                        new
                        {
                            Id = 102,
                            Abstract = "Анализ на новите методи за стабилизиране на кубити.",
                            Doi = "10.1126/science.abn0002",
                            Journal = "Наука",
                            PublicationType = "Научна статия",
                            Title = "Напредък в квантовите изчисления",
                            Year = 2023
                        },
                        new
                        {
                            Id = 103,
                            Doi = "10.1016/j.ecotod.2021.0003",
                            Journal = "Икономика днес",
                            PublicationType = "Доклад от конференция",
                            Title = "Изкуствен интелект във финансите",
                            Year = 2021
                        },
                        new
                        {
                            Id = 104,
                            Abstract = "Картографиране на генома при редки заболявания.",
                            Doi = "10.1016/j.cell.2020.0004",
                            Journal = "Клетка",
                            PublicationType = "Научна статия",
                            Title = "Генетика и наследствени заболявания",
                            Year = 2020
                        },
                        new
                        {
                            Id = 105,
                            Doi = "10.5555/nano-book-2023",
                            Journal = "Издателство 'Наука'",
                            PublicationType = "Монография",
                            Title = "Нови материали в нанотехнологиите",
                            Year = 2023
                        });
                });

            modelBuilder.Entity("ScientificAuthorsDB.Models.PublicationField", b =>
                {
                    b.Property<int>("PublicationId")
                        .HasColumnType("int");

                    b.Property<int>("ResearchFieldId")
                        .HasColumnType("int");

                    b.HasKey("PublicationId", "ResearchFieldId");

                    b.HasIndex("ResearchFieldId");

                    b.ToTable("PublicationFields");

                    b.HasData(
                        new
                        {
                            PublicationId = 1,
                            ResearchFieldId = 1
                        },
                        new
                        {
                            PublicationId = 1,
                            ResearchFieldId = 2
                        },
                        new
                        {
                            PublicationId = 2,
                            ResearchFieldId = 3
                        },
                        new
                        {
                            PublicationId = 3,
                            ResearchFieldId = 3
                        },
                        new
                        {
                            PublicationId = 3,
                            ResearchFieldId = 4
                        },
                        new
                        {
                            PublicationId = 101,
                            ResearchFieldId = 101
                        },
                        new
                        {
                            PublicationId = 101,
                            ResearchFieldId = 106
                        },
                        new
                        {
                            PublicationId = 102,
                            ResearchFieldId = 102
                        },
                        new
                        {
                            PublicationId = 102,
                            ResearchFieldId = 101
                        },
                        new
                        {
                            PublicationId = 103,
                            ResearchFieldId = 101
                        },
                        new
                        {
                            PublicationId = 103,
                            ResearchFieldId = 107
                        },
                        new
                        {
                            PublicationId = 104,
                            ResearchFieldId = 104
                        },
                        new
                        {
                            PublicationId = 104,
                            ResearchFieldId = 106
                        },
                        new
                        {
                            PublicationId = 105,
                            ResearchFieldId = 105
                        },
                        new
                        {
                            PublicationId = 105,
                            ResearchFieldId = 102
                        });
                });

            modelBuilder.Entity("ScientificAuthorsDB.Models.ResearchField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ResearchFields");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Изкуствен интелект"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Машинно обучение"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Софтуерно инженерство"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Обектно-ориентирано програмиране"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Информатика"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Физика"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Математика"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Биология"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Химия"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Медицина"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Икономика"
                        });
                });

            modelBuilder.Entity("ScientificAuthorsDB.Models.AuthorInstitution", b =>
                {
                    b.HasOne("ScientificAuthorsDB.Models.Author", "Author")
                        .WithMany("AuthorInstitutions")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScientificAuthorsDB.Models.Institution", "Institution")
                        .WithMany("AuthorInstitutions")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("ScientificAuthorsDB.Models.AuthorPublication", b =>
                {
                    b.HasOne("ScientificAuthorsDB.Models.Author", "Author")
                        .WithMany("AuthorPublications")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScientificAuthorsDB.Models.Publication", "Publication")
                        .WithMany("AuthorPublications")
                        .HasForeignKey("PublicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Publication");
                });

            modelBuilder.Entity("ScientificAuthorsDB.Models.PublicationField", b =>
                {
                    b.HasOne("ScientificAuthorsDB.Models.Publication", "Publication")
                        .WithMany("PublicationFields")
                        .HasForeignKey("PublicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScientificAuthorsDB.Models.ResearchField", "ResearchField")
                        .WithMany("PublicationFields")
                        .HasForeignKey("ResearchFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publication");

                    b.Navigation("ResearchField");
                });

            modelBuilder.Entity("ScientificAuthorsDB.Models.Author", b =>
                {
                    b.Navigation("AuthorInstitutions");

                    b.Navigation("AuthorPublications");
                });

            modelBuilder.Entity("ScientificAuthorsDB.Models.Institution", b =>
                {
                    b.Navigation("AuthorInstitutions");
                });

            modelBuilder.Entity("ScientificAuthorsDB.Models.Publication", b =>
                {
                    b.Navigation("AuthorPublications");

                    b.Navigation("PublicationFields");
                });

            modelBuilder.Entity("ScientificAuthorsDB.Models.ResearchField", b =>
                {
                    b.Navigation("PublicationFields");
                });
#pragma warning restore 612, 618
        }
    }
}
