// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScientificAuthorsDB.Data;

#nullable disable

namespace ScientificAuthorsDB.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260510214356_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ScientificAuthorsDB.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BirthYear")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OrcidId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthYear = 1975,
                            Email = "ivan@su.bg",
                            FirstName = "Иван",
                            LastName = "Петров",
                            OrcidId = "0000-0001-2345-6789"
                        },
                        new
                        {
                            Id = 2,
                            BirthYear = 1980,
                            Email = "maria@bas.bg",
                            FirstName = "Мария",
                            LastName = "Иванова",
                            OrcidId = "0000-0002-9876-5432"
                        },
                        new
                        {
                            Id = 3,
                            BirthYear = 1990,
                            Email = "g.dimitrov@tu.bg",
                            FirstName = "Георги",
                            LastName = "Димитров",
                            OrcidId = "0000-0003-1111-2222"
                        },
                        new
                        {
                            Id = 4,
                            BirthYear = 1978,
                            Email = "jsmith@mit.edu",
                            FirstName = "Джон",
                            LastName = "Смит",
                            OrcidId = "0000-0002-4444-5555"
                        },
                        new
                        {
                            Id = 5,
                            BirthYear = 1985,
                            Email = "elena.n@mu-plovdiv.bg",
                            FirstName = "Елена",
                            LastName = "Николова",
                            OrcidId = "0000-0001-7777-8888"
                        },
                        new
                        {
                            Id = 6,
                            BirthYear = 1982,
                            Email = "alice.j@oxford.ac.uk",
                            FirstName = "Алис",
                            LastName = "Джонсън",
                            OrcidId = "0000-0002-3333-6666"
                        },
                        new
                        {
                            Id = 7,
                            BirthYear = 1970,
                            Email = "p.todorov@unwe.bg",
                            FirstName = "Петър",
                            LastName = "Тодоров",
                            OrcidId = "0000-0003-9999-0000"
                        },
                        new
                        {
                            Id = 8,
                            BirthYear = 1965,
                            Email = "hmuller@mpg.de",
                            FirstName = "Ханс",
                            LastName = "Мюлер",
                            OrcidId = "0000-0001-5555-4444"
                        },
                        new
                        {
                            Id = 9,
                            BirthYear = 1988,
                            Email = "smiteva@cern.ch",
                            FirstName = "Силвия",
                            LastName = "Митева",
                            OrcidId = "0000-0002-1234-5678"
                        },
                        new
                        {
                            Id = 10,
                            BirthYear = 1992,
                            Email = "rbrown@stanford.edu",
                            FirstName = "Робърт",
                            LastName = "Браун",
                            OrcidId = "0000-0002-8888-1111"
                        });
                });

            modelBuilder.Entity("ScientificAuthorsDB.Models.AuthorInstitution", b =>
                {
                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("int");

                    b.Property<int?>("EndYear")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StartYear")
                        .HasColumnType("int");

                    b.HasKey("AuthorId", "InstitutionId");

                    b.HasIndex("InstitutionId");

                    b.ToTable("AuthorInstitutions");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            InstitutionId = 1,
                            Role = "Професор",
                            StartYear = 2010
                        },
                        new
                        {
                            AuthorId = 1,
                            InstitutionId = 3,
                            Role = "Гост-изследовател",
                            StartYear = 2015
                        },
                        new
                        {
                            AuthorId = 2,
                            InstitutionId = 3,
                            Role = "Главен асистент",
                            StartYear = 2012
                        },
                        new
                        {
                            AuthorId = 3,
                            InstitutionId = 5,
                            Role = "Доцент",
                            StartYear = 2018
                        },
                        new
                        {
                            AuthorId = 4,
                            InstitutionId = 2,
                            Role = "Професор",
                            StartYear = 2005
                        },
                        new
                        {
                            AuthorId = 5,
                            InstitutionId = 8,
                            Role = "Асистент",
                            StartYear = 2020
                        },
                        new
                        {
                            AuthorId = 6,
                            InstitutionId = 4,
                            Role = "Изследовател",
                            StartYear = 2016
                        },
                        new
                        {
                            AuthorId = 7,
                            InstitutionId = 10,
                            Role = "Професор",
                            StartYear = 2008
                        },
                        new
                        {
                            AuthorId = 8,
                            InstitutionId = 9,
                            Role = "Директор",
                            StartYear = 2000
                        },
                        new
                        {
                            AuthorId = 9,
                            InstitutionId = 6,
                            Role = "Физик",
                            StartYear = 2019
                        },
                        new
                        {
                            AuthorId = 10,
                            InstitutionId = 7,
                            Role = "Докторант",
                            StartYear = 2021
                        });
                });

            modelBuilder.Entity("ScientificAuthorsDB.Models.AuthorPublication", b =>
                {
                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("PublicationId")
                        .HasColumnType("int");

                    b.Property<int?>("AuthorOrder")
                        .HasColumnType("int");

                    b.Property<string>("ContributionRole")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuthorId", "PublicationId");

                    b.HasIndex("PublicationId");

                    b.ToTable("AuthorPublications");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            PublicationId = 1,
                            AuthorOrder = 1,
                            ContributionRole = "Водещ автор"
                        },
                        new
                        {
                            AuthorId = 5,
                            PublicationId = 1,
                            AuthorOrder = 2,
                            ContributionRole = "Съавтор"
                        },
                        new
                        {
                            AuthorId = 9,
                            PublicationId = 2,
                            AuthorOrder = 1,
                            ContributionRole = "Водещ автор"
                        },
                        new
                        {
                            AuthorId = 4,
                            PublicationId = 2,
                            AuthorOrder = 2,
                            ContributionRole = "Съавтор"
                        },
                        new
                        {
                            AuthorId = 7,
                            PublicationId = 3,
                            AuthorOrder = 1,
                            ContributionRole = "Водещ автор"
                        },
                        new
                        {
                            AuthorId = 10,
                            PublicationId = 3,
                            AuthorOrder = 2,
                            ContributionRole = "Съавтор"
                        },
                        new
                        {
                            AuthorId = 5,
                            PublicationId = 4,
                            AuthorOrder = 1,
                            ContributionRole = "Единствен автор"
                        },
                        new
                        {
                            AuthorId = 3,
                            PublicationId = 5,
                            AuthorOrder = 1,
                            ContributionRole = "Водещ автор"
                        },
                        new
                        {
                            AuthorId = 8,
                            PublicationId = 5,
                            AuthorOrder = 2,
                            ContributionRole = "Съавтор"
                        },
                        new
                        {
                            AuthorId = 1,
                            PublicationId = 6,
                            AuthorOrder = 1,
                            ContributionRole = "Водещ автор"
                        },
                        new
                        {
                            AuthorId = 3,
                            PublicationId = 6,
                            AuthorOrder = 2,
                            ContributionRole = "Съавтор"
                        },
                        new
                        {
                            AuthorId = 10,
                            PublicationId = 6,
                            AuthorOrder = 3,
                            ContributionRole = "Съавтор"
                        },
                        new
                        {
                            AuthorId = 9,
                            PublicationId = 7,
                            AuthorOrder = 1,
                            ContributionRole = "Водещ автор"
                        },
                        new
                        {
                            AuthorId = 6,
                            PublicationId = 7,
                            AuthorOrder = 2,
                            ContributionRole = "Съавтор"
                        },
                        new
                        {
                            AuthorId = 2,
                            PublicationId = 8,
                            AuthorOrder = 1,
                            ContributionRole = "Единствен автор"
                        },
                        new
                        {
                            AuthorId = 5,
                            PublicationId = 9,
                            AuthorOrder = 1,
                            ContributionRole = "Водещ автор"
                        },
                        new
                        {
                            AuthorId = 6,
                            PublicationId = 9,
                            AuthorOrder = 2,
                            ContributionRole = "Съавтор"
                        },
                        new
                        {
                            AuthorId = 7,
                            PublicationId = 10,
                            AuthorOrder = 1,
                            ContributionRole = "Водещ автор"
                        },
                        new
                        {
                            AuthorId = 3,
                            PublicationId = 11,
                            AuthorOrder = 1,
                            ContributionRole = "Главен изследовател"
                        },
                        new
                        {
                            AuthorId = 9,
                            PublicationId = 12,
                            AuthorOrder = 1,
                            ContributionRole = "Единствен автор"
                        },
                        new
                        {
                            AuthorId = 2,
                            PublicationId = 13,
                            AuthorOrder = 1,
                            ContributionRole = "Координатор"
                        },
                        new
                        {
                            AuthorId = 8,
                            PublicationId = 13,
                            AuthorOrder = 2,
                            ContributionRole = "Рецензент"
                        },
                        new
                        {
                            AuthorId = 5,
                            PublicationId = 14,
                            AuthorOrder = 1,
                            ContributionRole = "Водещ автор"
                        },
                        new
                        {
                            AuthorId = 7,
                            PublicationId = 15,
                            AuthorOrder = 1,
                            ContributionRole = "Единствен автор"
                        });
                });

            modelBuilder.Entity("ScientificAuthorsDB.Models.Institution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Institutions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "София",
                            Country = "България",
                            Name = "Софийски университет",
                            Type = "Университет",
                            Website = "https://www.uni-sofia.bg"
                        },
                        new
                        {
                            Id = 2,
                            City = "Кеймбридж",
                            Country = "САЩ",
                            Name = "МИТ (MIT)",
                            Type = "Университет",
                            Website = "https://www.mit.edu"
                        },
                        new
                        {
                            Id = 3,
                            City = "София",
                            Country = "България",
                            Name = "БАН",
                            Type = "Изследователски център",
                            Website = "https://www.bas.bg"
                        },
                        new
                        {
                            Id = 4,
                            City = "Оксфорд",
                            Country = "Великобритания",
                            Name = "Оксфордски университет",
                            Type = "Университет",
                            Website = "https://www.ox.ac.uk"
                        },
                        new
                        {
                            Id = 5,
                            City = "София",
                            Country = "България",
                            Name = "Технически университет",
                            Type = "Университет",
                            Website = "https://tu-sofia.bg"
                        },
                        new
                        {
                            Id = 6,
                            City = "Женева",
                            Country = "Швейцария",
                            Name = "ЦЕРН",
                            Type = "Изследователски център",
                            Website = "https://home.cern"
                        },
                        new
                        {
                            Id = 7,
                            City = "Станфорд",
                            Country = "САЩ",
                            Name = "Станфордски университет",
                            Type = "Университет",
                            Website = "https://www.stanford.edu"
                        },
                        new
                        {
                            Id = 8,
                            City = "Пловдив",
                            Country = "България",
                            Name = "Медицински университет",
                            Type = "Университет",
                            Website = "https://mu-plovdiv.bg"
                        },
                        new
                        {
                            Id = 9,
                            City = "Мюнхен",
                            Country = "Германия",
                            Name = "Институт 'Макс Планк'",
                            Type = "Изследователски център",
                            Website = "https://www.mpg.de"
                        },
                        new
                        {
                            Id = 10,
                            City = "София",
                            Country = "България",
                            Name = "УНСС",
                            Type = "Университет",
                            Website = "https://www.unwe.bg"
                        });
                });

            modelBuilder.Entity("ScientificAuthorsDB.Models.Publication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abstract")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Doi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Journal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Publications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abstract = "Изследване на приложението на невронни мрежи за ранна диагностика.",
                            Doi = "10.1038/s41586-022-00001",
                            Journal = "Природа",
                            PublicationType = "Научна статия",
                            Title = "Машинно обучение в здравеопазването",
                            Year = 2022
                        },
                        new
                        {
                            Id = 2,
                            Abstract = "Анализ на новите методи за стабилизиране на кубити.",
                            Doi = "10.1126/science.abn0002",
                            Journal = "Наука",
                            PublicationType = "Научна статия",
                            Title = "Напредък в квантовите изчисления",
                            Year = 2023
                        },
                        new
                        {
                            Id = 3,
                            Doi = "10.1016/j.ecotod.2021.0003",
                            Journal = "Икономика днес",
                            PublicationType = "Доклад от конференция",
                            Title = "Изкуствен интелект във финансите",
                            Year = 2021
                        },
                        new
                        {
                            Id = 4,
                            Abstract = "Картографиране на генома при редки заболявания.",
                            Doi = "10.1016/j.cell.2020.0004",
                            Journal = "Клетка",
                            PublicationType = "Научна статия",
                            Title = "Генетика и наследствени заболявания",
                            Year = 2020
                        },
                        new
                        {
                            Id = 5,
                            Doi = "10.5555/nano-book-2023",
                            Journal = "Издателство 'Наука'",
                            PublicationType = "Монография",
                            Title = "Нови материали в нанотехнологиите",
                            Year = 2023
                        },
                        new
                        {
                            Id = 6,
                            Doi = "10.1109/TNNLS.2019.0006",
                            Journal = "Инженерни науки",
                            PublicationType = "Научна статия",
                            Title = "Алгоритми за оптимизация на невронни мрежи",
                            Year = 2019
                        },
                        new
                        {
                            Id = 7,
                            Abstract = "Моделиране на разпределението на тъмната материя в близките галактики.",
                            Doi = "10.3847/1538-4357/ac0007",
                            Journal = "Астрофизичен журнал",
                            PublicationType = "Научна статия",
                            Title = "Тъмна материя и структура на Вселената",
                            Year = 2022
                        },
                        new
                        {
                            Id = 8,
                            Doi = "10.1002/ecy.0008",
                            Journal = "Екология",
                            PublicationType = "Книга",
                            Title = "Влияние на климата върху биоразнообразието",
                            Year = 2021
                        },
                        new
                        {
                            Id = 9,
                            Doi = "10.1016/S0140-6736(20)0009",
                            Journal = "Списание Ланцет",
                            PublicationType = "Научна статия",
                            Title = "Разработване на ваксини чрез мРНК",
                            Year = 2020
                        },
                        new
                        {
                            Id = 10,
                            Doi = "10.1111/jofi.0010",
                            Journal = "Журнал по финанси",
                            PublicationType = "Доклад от конференция",
                            Title = "Криптовалути и икономическа стабилност",
                            Year = 2023
                        },
                        new
                        {
                            Id = 11,
                            Doi = "10.5555/techpol-2023-011",
                            Journal = "Институт за технологични политики",
                            PublicationType = "Доклад от конференция",
                            Title = "Анализ на киберсигурността в държавния сектор",
                            Year = 2023
                        },
                        new
                        {
                            Id = 12,
                            Abstract = "Теоретичен модел за изпарението на свръхмасивни черни дупки.",
                            Doi = "10.5555/su-thesis-2018-012",
                            Journal = "Софийски университет",
                            PublicationType = "Дисертация",
                            Title = "Еволюция на черните дупки",
                            Year = 2018
                        },
                        new
                        {
                            Id = 13,
                            Doi = "10.5555/moew-report-2022",
                            Journal = "Министерство на екологията",
                            PublicationType = "Монография",
                            Title = "Годишен доклад за състоянието на околната среда",
                            Year = 2022
                        },
                        new
                        {
                            Id = 14,
                            Abstract = "Обзор на най-новите клинични проучвания.",
                            Doi = "10.5555/medrev-2021-014",
                            Journal = "Медицински преглед",
                            PublicationType = "Научна статия",
                            Title = "Съвременни методи за лечение на диабет",
                            Year = 2021
                        },
                        new
                        {
                            Id = 15,
                            Doi = "10.5555/bas-econ-2023-015",
                            Journal = "Икономически институт",
                            PublicationType = "Доклад от конференция",
                            Title = "Въздействие на инфлацията върху малкия бизнес",
                            Year = 2023
                        });
                });

            modelBuilder.Entity("ScientificAuthorsDB.Models.PublicationField", b =>
                {
                    b.Property<int>("PublicationId")
                        .HasColumnType("int");

                    b.Property<int>("ResearchFieldId")
                        .HasColumnType("int");

                    b.HasKey("PublicationId", "ResearchFieldId");

                    b.HasIndex("ResearchFieldId");

                    b.ToTable("PublicationFields");

                    b.HasData(
                        new
                        {
                            PublicationId = 1,
                            ResearchFieldId = 1
                        },
                        new
                        {
                            PublicationId = 1,
                            ResearchFieldId = 6
                        },
                        new
                        {
                            PublicationId = 2,
                            ResearchFieldId = 2
                        },
                        new
                        {
                            PublicationId = 2,
                            ResearchFieldId = 1
                        },
                        new
                        {
                            PublicationId = 3,
                            ResearchFieldId = 1
                        },
                        new
                        {
                            PublicationId = 3,
                            ResearchFieldId = 7
                        },
                        new
                        {
                            PublicationId = 4,
                            ResearchFieldId = 4
                        },
                        new
                        {
                            PublicationId = 4,
                            ResearchFieldId = 6
                        },
                        new
                        {
                            PublicationId = 5,
                            ResearchFieldId = 5
                        },
                        new
                        {
                            PublicationId = 5,
                            ResearchFieldId = 2
                        },
                        new
                        {
                            PublicationId = 6,
                            ResearchFieldId = 1
                        },
                        new
                        {
                            PublicationId = 6,
                            ResearchFieldId = 3
                        },
                        new
                        {
                            PublicationId = 7,
                            ResearchFieldId = 2
                        },
                        new
                        {
                            PublicationId = 8,
                            ResearchFieldId = 4
                        },
                        new
                        {
                            PublicationId = 9,
                            ResearchFieldId = 6
                        },
                        new
                        {
                            PublicationId = 9,
                            ResearchFieldId = 4
                        },
                        new
                        {
                            PublicationId = 10,
                            ResearchFieldId = 7
                        },
                        new
                        {
                            PublicationId = 11,
                            ResearchFieldId = 1
                        },
                        new
                        {
                            PublicationId = 12,
                            ResearchFieldId = 2
                        },
                        new
                        {
                            PublicationId = 13,
                            ResearchFieldId = 4
                        },
                        new
                        {
                            PublicationId = 13,
                            ResearchFieldId = 5
                        },
                        new
                        {
                            PublicationId = 14,
                            ResearchFieldId = 6
                        },
                        new
                        {
                            PublicationId = 15,
                            ResearchFieldId = 7
                        });
                });

            modelBuilder.Entity("ScientificAuthorsDB.Models.ResearchField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ResearchFields");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Информатика"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Физика"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Математика"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Биология"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Химия"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Медицина"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Икономика"
                        });
                });

            modelBuilder.Entity("ScientificAuthorsDB.Models.AuthorInstitution", b =>
                {
                    b.HasOne("ScientificAuthorsDB.Models.Author", "Author")
                        .WithMany("AuthorInstitutions")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScientificAuthorsDB.Models.Institution", "Institution")
                        .WithMany("AuthorInstitutions")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("ScientificAuthorsDB.Models.AuthorPublication", b =>
                {
                    b.HasOne("ScientificAuthorsDB.Models.Author", "Author")
                        .WithMany("AuthorPublications")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScientificAuthorsDB.Models.Publication", "Publication")
                        .WithMany("AuthorPublications")
                        .HasForeignKey("PublicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Publication");
                });

            modelBuilder.Entity("ScientificAuthorsDB.Models.PublicationField", b =>
                {
                    b.HasOne("ScientificAuthorsDB.Models.Publication", "Publication")
                        .WithMany("PublicationFields")
                        .HasForeignKey("PublicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScientificAuthorsDB.Models.ResearchField", "ResearchField")
                        .WithMany("PublicationFields")
                        .HasForeignKey("ResearchFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publication");

                    b.Navigation("ResearchField");
                });

            modelBuilder.Entity("ScientificAuthorsDB.Models.Author", b =>
                {
                    b.Navigation("AuthorInstitutions");

                    b.Navigation("AuthorPublications");
                });

            modelBuilder.Entity("ScientificAuthorsDB.Models.Institution", b =>
                {
                    b.Navigation("AuthorInstitutions");
                });

            modelBuilder.Entity("ScientificAuthorsDB.Models.Publication", b =>
                {
                    b.Navigation("AuthorPublications");

                    b.Navigation("PublicationFields");
                });

            modelBuilder.Entity("ScientificAuthorsDB.Models.ResearchField", b =>
                {
                    b.Navigation("PublicationFields");
                });
#pragma warning restore 612, 618
        }
    }
}
