// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScientificAuthorsDB.Data;

#nullable disable

namespace ScientificAuthorsDB.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260504180149_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ScientificAuthorsDB.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BirthYear")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OrcidId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthYear = 1975,
                            Email = "ivan@su.bg",
                            FirstName = "Иван",
                            LastName = "Петров"
                        },
                        new
                        {
                            Id = 2,
                            BirthYear = 1980,
                            Email = "maria@bas.bg",
                            FirstName = "Мария",
                            LastName = "Иванова"
                        });
                });

            modelBuilder.Entity("ScientificAuthorsDB.Models.AuthorInstitution", b =>
                {
                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("int");

                    b.Property<int?>("EndYear")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StartYear")
                        .HasColumnType("int");

                    b.HasKey("AuthorId", "InstitutionId");

                    b.HasIndex("InstitutionId");

                    b.ToTable("AuthorInstitutions");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            InstitutionId = 1,
                            Role = "Professor"
                        },
                        new
                        {
                            AuthorId = 2,
                            InstitutionId = 3,
                            Role = "Researcher"
                        });
                });

            modelBuilder.Entity("ScientificAuthorsDB.Models.AuthorPublication", b =>
                {
                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("PublicationId")
                        .HasColumnType("int");

                    b.Property<int?>("AuthorOrder")
                        .HasColumnType("int");

                    b.Property<string>("ContributionRole")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuthorId", "PublicationId");

                    b.HasIndex("PublicationId");

                    b.ToTable("AuthorPublications");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            PublicationId = 1,
                            AuthorOrder = 1,
                            ContributionRole = "Lead Author"
                        },
                        new
                        {
                            AuthorId = 2,
                            PublicationId = 1,
                            AuthorOrder = 2,
                            ContributionRole = "Co-Author"
                        },
                        new
                        {
                            AuthorId = 2,
                            PublicationId = 2,
                            AuthorOrder = 1,
                            ContributionRole = "Lead Author"
                        });
                });

            modelBuilder.Entity("ScientificAuthorsDB.Models.Institution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Institutions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "София",
                            Country = "България",
                            Name = "Софийски университет",
                            Type = "University"
                        },
                        new
                        {
                            Id = 2,
                            City = "Cambridge",
                            Country = "САЩ",
                            Name = "MIT",
                            Type = "University"
                        },
                        new
                        {
                            Id = 3,
                            City = "София",
                            Country = "България",
                            Name = "БАН",
                            Type = "Research Center"
                        });
                });

            modelBuilder.Entity("ScientificAuthorsDB.Models.Publication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abstract")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Doi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Journal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Publications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Journal = "Nature",
                            PublicationType = "Article",
                            Title = "Machine Learning in Healthcare",
                            Year = 2022
                        },
                        new
                        {
                            Id = 2,
                            Journal = "Science",
                            PublicationType = "Article",
                            Title = "Quantum Computing Advances",
                            Year = 2023
                        });
                });

            modelBuilder.Entity("ScientificAuthorsDB.Models.PublicationField", b =>
                {
                    b.Property<int>("PublicationId")
                        .HasColumnType("int");

                    b.Property<int>("ResearchFieldId")
                        .HasColumnType("int");

                    b.HasKey("PublicationId", "ResearchFieldId");

                    b.HasIndex("ResearchFieldId");

                    b.ToTable("PublicationFields");

                    b.HasData(
                        new
                        {
                            PublicationId = 1,
                            ResearchFieldId = 1
                        },
                        new
                        {
                            PublicationId = 2,
                            ResearchFieldId = 2
                        });
                });

            modelBuilder.Entity("ScientificAuthorsDB.Models.ResearchField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ResearchFields");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Computer Science"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Physics"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Biology"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Chemistry"
                        });
                });

            modelBuilder.Entity("ScientificAuthorsDB.Models.AuthorInstitution", b =>
                {
                    b.HasOne("ScientificAuthorsDB.Models.Author", "Author")
                        .WithMany("AuthorInstitutions")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScientificAuthorsDB.Models.Institution", "Institution")
                        .WithMany("AuthorInstitutions")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("ScientificAuthorsDB.Models.AuthorPublication", b =>
                {
                    b.HasOne("ScientificAuthorsDB.Models.Author", "Author")
                        .WithMany("AuthorPublications")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScientificAuthorsDB.Models.Publication", "Publication")
                        .WithMany("AuthorPublications")
                        .HasForeignKey("PublicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Publication");
                });

            modelBuilder.Entity("ScientificAuthorsDB.Models.PublicationField", b =>
                {
                    b.HasOne("ScientificAuthorsDB.Models.Publication", "Publication")
                        .WithMany("PublicationFields")
                        .HasForeignKey("PublicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScientificAuthorsDB.Models.ResearchField", "ResearchField")
                        .WithMany("PublicationFields")
                        .HasForeignKey("ResearchFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publication");

                    b.Navigation("ResearchField");
                });

            modelBuilder.Entity("ScientificAuthorsDB.Models.Author", b =>
                {
                    b.Navigation("AuthorInstitutions");

                    b.Navigation("AuthorPublications");
                });

            modelBuilder.Entity("ScientificAuthorsDB.Models.Institution", b =>
                {
                    b.Navigation("AuthorInstitutions");
                });

            modelBuilder.Entity("ScientificAuthorsDB.Models.Publication", b =>
                {
                    b.Navigation("AuthorPublications");

                    b.Navigation("PublicationFields");
                });

            modelBuilder.Entity("ScientificAuthorsDB.Models.ResearchField", b =>
                {
                    b.Navigation("PublicationFields");
                });
#pragma warning restore 612, 618
        }
    }
}
